server.port=8080
spring.application.name=Hoptal
spring.datasource.url=jdbc:postgresql://localhost:5432/Hoptal
spring.datasource.username=beny_database
spring.datasource.password=mydatabasepassword
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
jwt.secret=hoptal_secret_key_chad_2025_secure
jwt.expiration=86400000